# headers and icon 
title: omertugrul
info: BsC EEE @ Bilkent
icon-pic: assets/img/Llama-scaled.jpeg

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
